title: Lerntagebuch BAIN von Alicja
author: Alicja
email: alicja.bednarzewska@stud.fhgr.ch
description: Lerntagebuch für das Modul BAIN
  

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-cayman
